[app]
name = "footnote_mobile"
stylized-name = "Footnote"
identifier = "wiki.footnote.app"
template-pack = "dioxus"

[apple]
development-team = "7X4L53VGR3"
plist-pairs = [
    ["NSLocalNetworkUsageDescription", "Footnote uses the local network to find and sync with Footnote running on other devices."]
]
entitlements-file = "ios.entitlements.plist"
