[application]
ios_info_plist = "packaging/ios.info.plist"
ios_entitlements = "packaging/ios.app.entitlements"
macos_entitlements = "packaging/macos.app.entitlements"

[bundle]
identifier = "wiki.footnote.app"
publisher = "Nate Hardt"
icon = ["assets/icon.png"]
resources = ["assets/*"]
