[application]
ios_info_plist = "ios.info.plist"
ios_entitlements = "ios.app.entitlements"
macos_entitlements = "macos.app.entitlements"

[bundle]
identifier = "wiki.footnote.app"
publisher = "Nate Hardt"
icon = ["assets/icon.png"]
resources = ["assets/*"]
