[application]
macos_entitlements = "platform_build/macos.app.entitlements"
android_manifest = "platform_build/AndroidManifest.xml"
android_main_activity = "platform_build/MainActivity.kt"
name = "Footnote"

[bundle]
identifier = "wiki.footnote.app"
publisher = "Nate Hardt"
icon = [
    "icons/icon.png",
    "icons/icon.icns",
    "icons/icon.ico"
]
asset_dir = "assets"
